languageCode = "ja-jp"
title = "ハイキング-ハイキング"
baseURL = "https://hiking.shimakyohsuke.com/"
theme = "hucore"
copyright = "&copy; <a href=\"/\">HIKING-HIKING</a>"
description = "知らない土地、知らない景色を知る為にぼちぼち歩いて行くブログ"

[params]
  description = "知らない土地、知らない景色を知る為にぼちぼち歩いて行くブログ"
  author = "SHIMA KYOHSUKE"
  sharingicons = false
  displayauthor = true
